stages:
  - lint
  - build
  - test

job_lint:
  stage: lint
  image: hoto/flake8
  before_script:
    - apk add --update git
  script:
    - git rev-parse --abbrev-ref HEAD
    - git merge-base origin/HEAD HEAD
    - git --no-pager diff --name-only $(git rev-parse --abbrev-ref HEAD) $(git merge-base origin/HEAD HEAD)
    - flake8 $(git --no-pager diff --name-only $(git rev-parse --abbrev-ref HEAD) $(git merge-base origin/HEAD HEAD))
  except:
    - microservices
  tags:
    - docker

job1:
  stage: build
  image: registry.getnoc.com/noc/nocmc/microservices:build
  variables:
    NOC_PG_DB: noc
    NOC_PG_USER: noc
    NOC_PG_PASSWORD: noc
    BRANCH: microservices
  services:
    - name: registry.getnoc.com/infrastructure/postgres:dev
      alias: postgres
    - name: registry.getnoc.com/infrastructure/mongo:dev
      alias: mongo
  before_script:
    - export NOC_PG_ADDRESSES=registry.getnoc.com-infrastructure-postgres:5432
    - export NOC_MONGO_ADDRESSES=registry.getnoc.com-infrastructure-mongo:27017
  script:
    - find . -type f -name "*.py" -print0 | xargs -0 python -m py_compile
    - /usr/bin/cythonize -i speedup/*.pyx
    - python ./manage.py migrate
  only:
    - microservices
  tags:
    - docker
